//Organização de cada adicional: Título, Preço, Inclusivo ou não
let recheiosDoces = [
    ["Adicionais", "checkbox"],
    ["Aveia", 2.50, true],
    ["Cobertura de caramelo", 2.50, true],
    ["Cobertura de chocolate", 2.50, true],
    ["Cobertura de morango", 2.50, true],
    ["Mel", 2.50, true],
    ["Granulado", 2.50, true],
    ["Doce de leite", 2.50, true],
    ["Paçoca", 2.75, true],
    ["Banana", 3.00, true],
    ["Bis branco", 3.00, true],
    ["Bis preto", 3.00, true],
    ["Chantilly", 3.00, true],
    ["Coco ralado", 3.00, true],
    ["Granola", 3.00, true],
    ["Farinha lactea", 3.00, true],
    ["Sonho de valsa", 3.00, true],
    ["Sucrilhos", 3.00, true],
    ["Pó de guaraná", 3.00, true],
    ["Ouro branco", 3.00, true],
    ["Goiabada", 3.00, true],
    ["Abacaxi", 3.50, true],
    ["Chocolate branco", 5.00, true],
    ["Chocolate", 5.00, true],
    ["Confete", 3.50, true],
    ["Leite condensado", 3.50, true],
    ["Space boll", 3.50, true],
    ["Polpa de fruta abacaxi", 3.75, true],
    ["Polpa de fruta abacaxi ao vinho", 3.75, true],
    ["Polpa de fruta ameixa", 3.75, true],
    ["Polpa de fruta amora", 3.75, true],
    ["Polpa de frutas vermelhas", 3.75, true],
    ["Polpa de fruta maracujá", 3.75, true],
    ["Polpa de fruta morango", 3.75, true],
    ["Creme de paçoca", 3.99, true],
    ["Ovomaltine", 3.50, true],
    ["Leite Ninho", 4.00, true],
    ["Morango", 4.00, true],
    ["Manga", 4.50, true],
    ["Creme de avelã", 4.50, true],
    ["Castanha", 4.50, true],
    ["Creme de ouro branco", 4.50, true],
    ["Cupuaçu", 4.50, true],
    ["Creme de valsa", 4.50, true],
    ["Kit kat", 6.00, true],
    ["Pasta de amendoim", 4.99, true],
    ["Whey protein", 4.99, true],
    ["Kiwi", 5.00, true],
    ["Creme laka", 5.00, true],
    ["Creme de leite ninho", 5.00, true],
    ["Creme de lacta com óreo", 5.00, true],
    ["Creme cocco bianco", 5.00, true],
    ["Chocolate suflair", 3.99, false],
    ["Creme de morango", 5.00, false],
    ["Creme de ovomaltine", 5.50, false],
    ["Creme de kit kat", 5.50, false],
    ["Cereja", 6.00, false],
    ["Creme de pistache", 6.50, false],
    ["Creme de avelã x2", 7.00, false],
    ["Ferrero rocher", 9.50, false],
    ["Kinder bueno" , 12.00, false]
];
let recheiosSalgados = [
    ["Adicionais", "checkbox"],
    ["Bacon", 4.99, false],
    ["Catupiry", 4.99, false],
    ["Cheddar", 4.99, false],
    ["Creme de alho", 3.00, false],
    ["Hambúrguer", 4.00, false],
    ["Mussarela", 4.00, false],
    ["Ovo", 2.00, false],
    ["Presunto", 4.00, false],
    ["Salada", 4.00, false],
];
let bordasPizza = [
    ["Bordas Recheadas", "radio"],
    ["Borda: Doce de leite", 16.00, false],
    ["Borda: Goiabada", 16.00, false],
    ["Borda: Queijo com bacon", 21.00, false],
    ["Borda: Catupiry com bacon", 19.00, false],
    ["Borda: Chocolate com queijo", 20.00, false],
    ["Borda: Cheddar com bacon", 21.00, false],
    ["Borda: Musarela", 21.00, false],
    ["Borda: Catupiry", 16.00, false],
    ["Borda: Cheddar", 16.00, false],
    ["Borda: Creme de avelã", 16.00, false]
];

export let adicionais = [false, recheiosDoces, recheiosSalgados, bordasPizza]





