export let salgadaGrande = [
    [2, "salgadaGrande", "Pizzas Grandes", [3], 1],
    ["Carne seca acebolada (Grande)", "Carne seca desfiada , molho de tomate especial, mussarela, cebola, azeitona e orégano", 68.00, 0],
    ["Carne seca cremosa (Grande)", "Carne seca desfiada ,molho especial, mussarela, catupiry, orégano", 73.00, 0],
    ["Carne seca ao alho (Grande)", "Carne seca desfiada, molho de tomate especial, alho frito, mussarela , azeite , azeitona e cebola", 71.00, 0],
    ["Carne seca especial (Grande)", "Carne seca desfiada, molho de tomate especial, cebola , catupiry, mussarela , tomate , bacon , azeitona e orégano", 76.00, 0],
    ["Costela acebolada (Grande)", "Costela desfiado, molho de tomate especial, mussarela, cebola, azeitona e orégano", 68.00, 0],
    ["Costela cremosa (Grande)", "Costela desfiada ,molho especial, mussarela, catupiry, orégano", 73.00, 0],
    ["Costela ao alho (Grande)", "Costela desfiada, molho de tomate especial, alho frito, mussarela , azeite , azeitona e cebola", 71.00, 0] ,
    ["Costela especial (Grande)", "Costela desfiada, molho de tomate especial, cebola , catupiry, mussarela , tomate , bacon , azeitona e orégano", 76.00, 0],
    ["Cupim acebolado (Grande)", "Cupim desfiado, molho de tomate especial, mussarela, cebola, azeitona e orégano", 65.00, 0],
    ["Cupim cremoso (Grande)", "Cupim desfiado, molho especial, mussarela, catupiry, orégano", 70, 0],
    ["Cupim ao alho (Grande)", "Cupim desfiado, molho de tomate especial, cebola, alho frito, mussarela , azeite , azeitona", 68, 0],
    ["Cupim especial (Grande)", "Cupim desfiado, molho de tomate especial, cebola , catupiry, mussarela , tomate , bacon , azeitona e orégano", 73, 0],
    ["Pizza Alho e óleo (Grande)", "Mussarela, bacon, alho, tomate, cebola, orégano e azeitona ", 70.00, 0],
    ["Pizza Baiana (Grande)", "Mussarela, calabresa picada, parmesão, pimenta, ovos, pimentão, tomate, cebola, orégano e azeitona", 75.00, 0],
    ["Pizza Brócolis (Grande)", "Brócolis, bacon fatiado, mussarela e catupiry", 75.00, 0],
    ["Pizza Calabresa (Grande)", "Calabresa, mussarela, cebola, tomate, orégano, molho de tomate", 65.00, 0],
    ["Pizza Carijó (Grande)", "Mussarela, molho, frango, ovo, catupiry, milho, orégano e azeitona", 70.00, 0],
    ["Pizza Fazendinha (Grande)", "Presunto, mussarela, ovo, tomate, milho e cebola", 70.00, 0],
    ["Pizza Frango com catupiry (Grande)", "Mussarela, frango, catupiry, orégano, tomate, azeitona e molho de tomate", 65.00, 0],
    ["Pizza Frango cremoso (Grande)", "Frango, catupiry, batata palha, azeitona fatiada, mussarela e orégano", 72.00, 0],
    ["Pizza Franlone (Grande)", "Frango, queijo provolone, tomate, mussarela, orégano, azeitona, milho e molho de tomate", 70.00, 0],
    ["Pizza Hot Dog (Grande)", "Salsicha ao molho, batata palha, catchup, maioneses, mussarela e milho", 65.00, 0],
    ["Pizza Lombinho especial (Grande)", "Lombo canadense, presunto, mussarela, tomate e orégano", 75.00, 0],
    ["Pizza Lombo canadense (Grande)", "Lombo canadense, presunto, mussarela, tomate, orégano, molho de tomate, palmito e catupiry", 70.00, 0],
    ["Pizza Marajá (Grande)", "Mussarela, lombo, canadense, catupiry, palmito, bacon, orégano, calabresa, champignon, azeitona e tomate", 78.00, 0],
    ["Pizza Maromba (Grande)", "Frango, catupiry, ovos, mussarela, orégano, bacon, tomate e molho especial", 75.00, 0],
    ["Pizza Moda da casa (Grande)", "Presunto, mussarela, calabresa, bacon, catupiry, tomate, cebola, orégano, e molho de tomate", 78.00, 0],
    ["Pizza Mussarela (Grande)", "Mussarela, molho gourmet de tomate, azeitona, tomate e orégano", 75.00, 0],
    ["Pizza Napolitana (Grande)", "Tomate, azeite, orégano, alho e mussarela", 65.00, 0],
    ["Pizza Parmegiana (Grande)", "Presunto, queijo, provolono, mussarela, molho de tomate, baconorégano, azeitona e tomate", 75.00, 0],
    ["Pizza Portuguesa (Grande)", "Presunto, mussarela, bacon, ovo, azeitona, tomate, palmito, cebola e molho de tomate", 65.00, 0],
    ["Pizza Presunto Mussarela (Grande)", "Presunto, mussarela, orégano, tomate e molho de tomate", 65.00, 0],
    ["Pizza Quatro queijos (Grande)", "Mussarela, queijo provolone, queijo parmesão, catupiry, tomate, orégano, azeitona e tomate", 78.00, 0],
    ["Pizza Siciliana (Grande)", "Mussarela, calabresa, parmesão, bacon, pimentão, cebola, tomate, orégano e azeitona", 75.00, 0],
    ["Pizza Soft (Grande)", "Mussarela, calabresa picada, champignon, cebola, bacon, tomate, catupiry, orégano e azeitona", 75.00, 0],
    ["Pizza Vegetariana (Grande)", "Milho, palmito, brócolis, champignon, mussarela e couve", 75.00, 0]
];
let salgadaMedia = [
    [2, "salgadaMedia", "Pizzas Médias", [3], 1],
    ["Carne seca acebolada (Média)", "Carne seca desfiada , molho de tomate especial, mussarela, cebola, azeitona e orégano", 48.00, 0],
    ["Carne seca cremosa (Média)", "Carne seca desfiada ,molho especial, mussarela, catupiry, orégano", 48.00, 0],
    ["Carne seca ao alho (Média)", "Carne seca desfiada, molho de tomate especial, alho frito, mussarela , azeite , azeitona e cebola", 48.00, 0],
    ["Carne seca especial (Média)", "Carne seca desfiada, molho de tomate especial, cebola , catupiry, mussarela , tomate , bacon , azeitona e orégano", 48.00, 0],
    ["Costela acebolada (Média)", "Costela desfiado, molho de tomate especial, mussarela, cebola, azeitona e orégano", 48.00, 0],
    ["Costela cremosa (Média)", "Costela desfiada ,molho especial, mussarela, catupiry, orégano", 48.00, 0],
    ["Costela ao alho (Média)", "Costela desfiada, molho de tomate especial, alho frito, mussarela , azeite , azeitona e cebola", 48.00, 0] ,
    ["Costela especial (Média)", "Costela desfiada, molho de tomate especial, cebola , catupiry, mussarela , tomate , bacon , azeitona e orégano", 48.00, 0],
    ["Cupim acebolado (Média)", "Cupim desfiado, molho de tomate especial, mussarela, cebola, azeitona e orégano", 48.00, 0],
    ["Cupim cremoso (Média)", "Cupim desfiado, molho especial, mussarela, catupiry, orégano", 48, 0],
    ["Cupim ao alho (Média)", "Cupim desfiado, molho de tomate especial, cebola, alho frito, mussarela , azeite , azeitona", 48, 0],
    ["Cupim especial (Média)", "Cupim desfiado, molho de tomate especial, cebola , catupiry, mussarela , tomate , bacon , azeitona e orégano", 48, 0],
    ["Pizza Alho e óleo (Média)", "Mussarela, bacon, alho, tomate, cebola, orégano e azeitona ", 45.00, 0],
    ["Pizza Baiana (Média)", "Mussarela, calabresa picada, parmesão, pimenta, ovos, pimentão, tomate, cebola, orégano e azeitona", 48.00, 0],
    ["Pizza Brócolis (Média)", "Brócolis, bacon fatiado, mussarela e catupiry", 48.00, 0],
    ["Pizza Calabresa (Média)", "Calabresa, mussarela, cebola, tomate, orégano, molho de tomate", 45.00, 0],
    ["Pizza Carijó (Média)", "Mussarela, molho, frango, ovo, catupiry, milho, orégano e azeitona", 45.00, 0],
    ["Pizza Fazendinha (Média)", "Presunto, mussarela, ovo, tomate, milho e cebola", 45.00, 0],
    ["Pizza Frango com catupiry (Média)", "Mussarela, frango, catupiry, orégano, tomate, azeitona e molho de tomate", 45.00, 0],
    ["Pizza Frango cremoso (Média)", "Frango, catupiry, batata palha, azeitona fatiada, mussarela e orégano", 45.00, 0],
    ["Pizza Franlone (Média)", "Frango, queijo provolone, tomate, mussarela, orégano, azeitona, milho e molho de tomate", 45.00, 0],
    ["Pizza Hot Dog (Média)", "Salsicha ao molho, batata palha, catchup, maioneses, mussarela e milho", 45.00, 0],
    ["Pizza Lombinho especial (Média)", "Lombo canadense, presunto, mussarela, tomate e orégano", 48.00, 0],
    ["Pizza Lombo canadense (Média)", "Lombo canadense, presunto, mussarela, tomate, orégano, molho de tomate, palmito e catupiry", 45.00, 0],
    ["Pizza Marajá (Média)", "Mussarela, lombo, canadense, catupiry, palmito, bacon, orégano, calabresa, champignon, azeitona e tomate", 48.00, 0],
    ["Pizza Maromba (Média)", "Frango, catupiry, ovos, mussarela, orégano, bacon, tomate e molho especial", 48.00, 0],
    ["Pizza Moda da casa (Média)", "Presunto, mussarela, calabresa, bacon, catupiry, tomate, cebola, orégano, e molho de tomate", 48.00, 0],
    ["Pizza Mussarela (Média)", "Mussarela, molho gourmet de tomate, azeitona, tomate e orégano", 48.00, 0],
    ["Pizza Napolitana (Média)", "Tomate, azeite, orégano, alho e mussarela", 45.00, 0],
    ["Pizza Parmegiana (Média)", "Presunto, queijo, provolono, mussarela, molho de tomate, baconorégano, azeitona e tomate", 48.00, 0],
    ["Pizza Portuguesa (Média)", "Presunto, mussarela, bacon, ovo, azeitona, tomate, palmito, cebola e molho de tomate", 45.00, 0],
    ["Pizza Presunto Mussarela (Média)", "Presunto, mussarela, orégano, tomate e molho de tomate", 45.00, 0],
    ["Pizza Quatro queijos (Média)", "Mussarela, queijo provolone, queijo parmesão, catupiry, tomate, orégano, azeitona e tomate", 48.00, 0],
    ["Pizza Siciliana (Média)", "Mussarela, calabresa, parmesão, bacon, pimentão, cebola, tomate, orégano e azeitona", 48.00, 0],
    ["Pizza Soft (Média)", "Mussarela, calabresa picada, champignon, cebola, bacon, tomate, catupiry, orégano e azeitona", 48.00, 0],
    ["Pizza Vegetariana (Média)", "Milho, palmito, brócolis, champignon, mussarela e couve", 48.00, 0]
]
export let doceGrande = [
    [2, "doceGrande", "Pizzas Doces (Grande)", [3], 1],
    ["Açai com leite ninho","Pizza Doce (Grande)",  70.00, 0],
    ["Açai com morango e nutella","Pizza Doce (Grande)",  70.00, 0],
    ["Banana, canela, queijo, calda de caramelo","Pizza Doce (Grande)",  70.00, 0],
    ["Creme ninho com morango","Pizza Doce (Grande)",  70.00, 0],
    ["Diamante negro","Pizza Doce (Grande)",  70.00, 0],
    ["Doce de leite com queijo","Pizza Doce (Grande)",  70.00, 0],
    ["Goiabada com queijo","Pizza Doce (Grande)",  70.00, 0],
    ["Laka", "Pizza Doce (Grande)", 70.00, 0],
    ["Laka óreo", "Pizza Doce (Grande)", 70.00, 0],
    ["Creme de avelã, morango, coco ralado, leite condensado e bis preto","Pizza Doce (Grande)",  70.00, 0],
    ["Creme de avelã", "Pizza Doce (Grande)", 70.00, 0],
    ["Creme de avelã com kit kat","Pizza Doce (Grande)",  70.00, 0],
    ["Creme de avelã com morango","Pizza Doce (Grande)",  70.00, 0],
    ["Creme de avelã e confete","Pizza Doce (Grande)",  70.00, 0],
    ["Creme de avelã morango e confete","Pizza Doce (Grande)",  70.00, 0],
    ["Ouro branco", "Pizza Doce (Grande)", 70.00, 0],
    ["Prestígio", "Pizza Doce (Grande)", 70.00, 0],
    ["Sonho de valsa", "Pizza Doce (Grande)", 70.00, 0]
];
let doceMedia = [
    [2, "doceMedia", "Pizzas Doces (Média)", [0], 1],
    ["Açai com leite ninho","Pizza Doce (Média)",  48.00, 0],
    ["Açai com morango e nutella","Pizza Doce (Média)",  48.00, 0],
    ["Banana, canela, queijo, calda de caramelo","Pizza Doce (Média)",  48.00, 0],
    ["Creme ninho com morango","Pizza Doce (Média)",  48.00, 0],
    ["Diamante negro", "Pizza Doce (Média)",  0],
    ["Doce de leite com queijo","Pizza Doce (Média)",  48.00, 0],
    ["Goiabada com queijo","Pizza Doce (Média)",  48.00, 0],
    ["Laka", "Pizza Doce (Média)", 48.00, 0],
    ["Laka óreo", "Pizza Doce (Média)", 48.00, 0],
    ["Creme de avelã, morango, coco ralado, leite condensado e bis preto","Pizza Doce (Média)",  48.00, 0],
    ["Creme de avelã", "Pizza Doce (Média)", 48.00, 0],
    ["Creme de avelã com kit kat","Pizza Doce (Média)",  48.00, 0],
    ["Creme de avelã com morango","Pizza Doce (Média)",  48.00, 0],
    ["Creme de avelã e confete","Pizza Doce (Média)",  48.00, 0],
    ["Creme de avelã morango e confete","Pizza Doce (Média)",  48.00, 0],
    ["Ouro branco", "Pizza Doce (Média)", 48.00, 0],
    ["Prestígio", "Pizza Doce (Média)", 48.00, 0],
    ["Sonho de valsa", "Pizza Doce (Média)", 48.00, 0]
];

export let doisSabores = [
    [4, "doisSabores", "Monte sua Pizza de 2 Sabores", [3], 2],
    ["Pizza 2 Sabores", "", 0.0, 0]
]

export let pizzas = ["pizzas", "Ver Pizzas", salgadaGrande, salgadaMedia, doceGrande, doceMedia, doisSabores]